Feature/sergeyro/tooltip on keyboard focus
mondaycom/monday-ui-react-core pull request #1107
Opened 2023-02-12 20:54 UTC by SergeyRoyt

https://monday.monday.com/boards/3532714909/pulses/3949004433

2023-02-14 07:18 UTC, orrgottlieb requested changes
The change should be in the infra of the Dialog, as it should map the relevant event to the corresponding keyboard events.

please reconsider the implementation

2023-02-14 07:18 UTC, orrgottlieb commented on src/components/BreadcrumbsBar/BreadcrumbItem/BreadcrumbItem.tsx
> +const SHOW_TRIGGERS = [HideShowEvent.FOCUS, HideShowEvent.MOUSE_ENTER];
this is redundant and not intuitive, should be a default for mouse_enter/mouse_leave, mouse_over

2023-02-14 07:18 UTC, orrgottlieb commented on src/components/ButtonGroup/ButtonWrapper.tsx
> +const SHOW_TRIGGERS = [HideShowEvent.FOCUS, HideShowEvent.MOUSE_ENTER];
same comment

2023-02-15 12:21 UTC, hadasfa reviewed
let's do here what we discuss - we will talk about it in our meeting

2023-02-21 15:39 UTC, closed without merging