Readme updates for easier contribution
mondaycom/monday-ui-react-core pull request #1344
Opened 2023-06-04 19:46 UTC by hadasfa

2023-06-05 19:04 UTC, shlomitc requested changes

2023-06-06 07:10 UTC, hadasfa commented on TESTING_README.md
> +3. Storybook interaction tests for more complex scenarios (more information regarding this subject later. More information about this [here](./src/tests/readme.md).
Wrote it later I think... I can write it here also

2023-06-06 07:11 UTC, hadasfa commented on TESTING_README.md
> +Use our plop, which automatically generates the proper folder structure. Snapshot tests and jest behavior testes files should end with .test.tsx, and storybook interaction tests files with .interacti
I want them to know that if they create new tests (even for already exist component) they need to use plop for that

2023-06-06 11:19 UTC, hadasfa commented on API_GUIDELINES.MD
> +3. **Child Component Prop**: If a component only accepts a string as a child component, we avoid using the `children` prop. Instead, use a separate prop called `text`.
it used to be our guideline so far, we experienced a lot of issues regarding node elements as children until now so I think it worth talking about it... I can remove this for now from the md file for not being a blocker in the initial stage

2023-06-06 13:28 UTC, hadasfa commented on CONTRIBUTING.md
>  ## Information about the project
mmm like what for example? what is missing from the flow of ## How to contribute?

2023-06-06 13:33 UTC, hadasfa commented on TESTING_README.md
>  2. [React testing library](https://testing-library.com/docs/react-testing-library/intro) as our components testing library
I did few changes there let me know what u think

2023-06-06 15:19 UTC, shlomitc approved these changes

2023-06-07 06:53 UTC, merged

2023-06-07 07:28 UTC, SergeyRoyt commented on API_GUIDELINES.MD
>  When testing the application code that uses vibe components, it is necessary to retrieve elements. for that, `data-testid`s are used (TODO - add a link to a guide about how to test).
There is a TODO here, maybe let's fix it?