Api changes/hadas/next
mondaycom/monday-ui-react-core pull request #1475
Opened 2023-08-15 07:52 UTC by hadasfa

#### Basic
- [ ] Used plop (`npm run plop`) to create a new component.
- [ ] PR has description.
- [ ] New component is functional and uses Hooks. 
- [ ] Component defines [`PropTypes`](https://reactjs.org/docs/typechecking-with-proptypes.html).
#### Style
- [ ] Styles are added to `NewComponent.modules.scss` file inside of the `NewComponent` folder.
- [ ] Component uses CSS Modules.
- [ ] Design is compatible with [Monday Design System](https://design.monday.com/).
#### Storybook
- [ ] Stories were added to `/src/NewComponent/__stories__/NewComponent.stories.js` file.
- [ ] Stories include all flows of using the component.
#### Tests
- [ ] Tests are compliant with [TESTING_README.md](TESTING_README.md) instructions.

2023-08-15 10:15 UTC, shlomitc requested changes

2023-08-15 10:15 UTC, shlomitc commented on package.json
> +    "monday-ui-style": "0.1.177",
not relevant for this PR

2023-08-15 10:15 UTC, shlomitc commented on rollup.config.js
> +  return `${name}_${getShortSha(content + loadPackageJsonResult.version)}`;
this looks like a mistake. the css module class name can't contain dots

2023-08-15 12:58 UTC, hadasfa commented on src/styles/typography.scss
> +    "text1": ("bold", "medium", "normal"),
not related just fix it while merging from master

2023-08-16 08:09 UTC, shlomitc approved these changes

2023-08-16 08:54 UTC, merged