feat: update label with VibeComponent
mondaycom/monday-ui-react-core pull request #1595
Opened 2023-10-03 13:05 UTC by jes14

make <Label> a VibeComponent and add ref forwarding (https://github.com/mondaycom/monday-ui-react-core/issues/1588)

2023-10-03 13:27 UTC, SergeyRoyt commented on src/components/Label/Label.tsx
> +    const mergedRef = useMergeRefs({ refs: [ref] });
`labelRef` should also be among mergedRefs

2023-10-03 14:15 UTC, SergeyRoyt requested changes
One issue to fix :)

2023-10-04 06:43 UTC, jes14 commented
Hi @SergeyRoyt 
Thanks a lot for your reviews. Just updated it.

2023-10-04 08:03 UTC, SergeyRoyt approved these changes
Looks great now!
Thanks a lot for your contribution! ❤️

2023-10-04 08:03 UTC, merged