docs: fix links
mondaycom/monday-ui-react-core pull request #1600
Opened 2023-10-03 15:25 UTC by Dhoni77

Fixes #1580.

- Fix spacing.
- Fix size.

2023-10-03 18:23 UTC, SergeyRoyt commented on src/storybook/stand-alone-documentaion/accessibility/accessibility.stories.mdx
> +  <Link href={accessibilityCheckList} target="_blank" size={Link.sizes.SMALL} withoutSpacing={false}>
```suggestion
  <Link href={accessibilityCheckList} size={Link.sizes.SMALL}>
```

2023-10-03 18:25 UTC, SergeyRoyt commented on src/storybook/stand-alone-documentaion/accessibility/accessibility.stories.mdx
>    To check color contrast in design use{" "}
```suggestion
  To check color contrast in design use
```

2023-10-03 18:25 UTC, SergeyRoyt commented on src/storybook/stand-alone-documentaion/accessibility/accessibility.stories.mdx
> +  >
```suggestion
  <Link href="https://www.figma.com/community/plugin/748533339900865323/Contrast" size={Link.sizes.SMALL}>
```

2023-10-03 18:28 UTC, SergeyRoyt commented on src/storybook/stand-alone-documentaion/accessibility/accessibility.stories.mdx
> +UI Components - Visual information required to identify active UI components and states (including borders for input elements (text input, radio buttons, checkboxes, etc.) as well as Focus Indicator
```suggestion
UI Components - Visual information required to identify active UI components and states, including borders for input elements (text input, radio buttons, checkboxes, etc.) as well as Focus Indicator (visible focus around active elements when they receive keyboard focus)<br/>
```

2023-10-03 18:28 UTC, SergeyRoyt requested changes
Left a few notes

2023-10-05 08:53 UTC, Dhoni77 commented
cc @SergeyRoyt

2023-10-08 09:24 UTC, SergeyRoyt approved these changes
Great, thanks!

2023-10-08 09:24 UTC, merged