test: add editable heading interaction test
mondaycom/monday-ui-react-core pull request #1612
Opened 2023-10-04 15:05 UTC by jes14

Update <EditableHeading> interaction tests (https://github.com/mondaycom/monday-ui-react-core/issues/1576)

2023-10-05 13:36 UTC, SergeyRoyt commented on src/components/EditableHeading/__tests__/editable-heading-interactions.tsx
> +});
Tried it out, but it didn't worked correctly
Used it as a draft though. Propose to change it like this

```suggestion
import { expect } from "@storybook/jest";
import {
  Canvas,
  clearText,
  clickElement,
  getByTestId,
  interactionSuite,
  typeText
} from "../../../tests/interactions-utils";
import { ComponentDefaultTestId } from "../../../tests/constants";
import { resetFocus } from "../../../__tests__/interactions-helper";

const getEditableHeadingHeading = async (canvas: Canvas) => {
  await resetFocus();
  return getByTestId(canvas, ComponentDefaultTestId.HEADING);
};

const getEditableHeadingInput = async (canvas: Canvas) => {
  await resetFocus();
  const editableHeadingElement = getByTestId(canvas, ComponentDefaultTestId.CLICKABLE);
  clickElement(editableHeadingElement);
  return getByTestId(canvas, ComponentDefaultTestId.EDITABLE_INPUT);
};

async function textSimpleText(canvas: Canvas) {
  const editableHeadingInput = await getEditableHeadingInput(canvas);
  await clearText(editableHeadingInput);

  const text = "Typed Text";
  await typeText(editableHeadingInput, text);
  expect(editableHeadingInput).toHaveAttribute("value", text);

  await resetFocus();
  const editableHeading = await getEditableHeadingHeading(canvas);
  expect(editableHeading).toHaveTextContent(text);
}

export const overviewPlaySuite = interactionSuite({
  tests: [textSimpleText]
});
```

2023-10-05 13:37 UTC, SergeyRoyt commented on src/components/EditableHeading/__stories__/EditableHeading.stories.mdx
> +    <EditableHeading type={EditableHeading.types.h1} placeholder="H1 Placeholder" ariaLabel="editableHeading"/>
This one is not really needed

2023-10-05 13:39 UTC, SergeyRoyt commented on src/components/EditableHeading/__stories__/EditableHeading.stories.mdx
Here to `<Story name="Overview"` you can add `play={overviewPlaySuite}`, this way the storybook will run this interaction test and you will be able to see it on the `Sandbox` tab. It'll also run automatically while running tests in Chromatic

2023-10-05 13:41 UTC, SergeyRoyt requested changes
Didn't work for me, proposed the fixed

2023-10-05 15:28 UTC, jes14 commented
Hi, @SergeyRoyt 
Thank you for your feedback. Your review was really helpful. I've updated from the feedback -> ready for review

2023-10-08 08:20 UTC, SergeyRoyt approved these changes
Great!
Thanks for the contribution, @jes14!

2023-10-08 08:20 UTC, merged