docs: <Checkbox> Usage guidelines - fix font #1577
mondaycom/monday-ui-react-core pull request #1621
Opened 2023-10-06 20:31 UTC by SoumyadiptoPal

Fixes issue #1577 
#### Basic

- [ ] Used plop (`npm run plop`) to create a new component.
- [ ] PR has description.
- [ ] New component is functional and uses Hooks.
- [ ] Component is written in TypeScript.

#### Style

- [ ] Styles are added to `NewComponent.modules.scss` file inside the `NewComponent` folder.
- [ ] Component uses CSS Modules.
- [ ] Design is compatible with [Monday Design System](https://design.monday.com/).
- [ ] Styles are defined using [monday-ui-style](https://github.com/mondaycom/monday-ui-style) tokens
- [ ] Displays correctly in all the themes

#### Storybook

- [ ] Stories were added to `/src/components/NewComponent/__stories__/NewComponent.stories.mdx` file.
- [ ] Stories include all flows of using the component.
- [ ] Stories implemented using [vibe-storybook-components](https://github.com/mondaycom/vibe-storybook-components) components and tokens.

#### Tests

- [ ] Tests are compliant with [TESTING_README.md](TESTING_README.md) instructions.

#### Accessibility

- [ ] Component is accessible.
- [ ] Component is compatible with [Vibe Accessibility Guidelines](https://style.monday.com/?path=/docs/foundations-accessibility--page)
![image](https://github.com/mondaycom/monday-ui-react-core/assets/119007659/e884db93-08b1-45f2-ba48-ff2b42708d06)

2023-10-06 20:33 UTC, SoumyadiptoPal commented
@SergeyRoyt I have fixed issue #1577

2023-10-08 10:35 UTC, SergeyRoyt commented on src/components/Checkbox/__stories__/checkbox.stories.scss
> +@import "~monday-ui-style/dist/mixins";
It's not needed here - no mixins from monday-ui-style are used

2023-10-08 10:43 UTC, SergeyRoyt commented on src/components/Checkbox/__stories__/checkbox.stories.scss
> +    font-family :var(--font-family) !important;
`font-family` is not the only thing to define the font. Let's instead use `sb-content-text` mixin and increase the specificity of selector, so all the styles would apply. Btw, even thought, it's only documentation using `!important` in general is a bad practice

I propose we'd do smth like this:
```suggestion
    span {
      @include sb-content-text;
    }
```


And also we'll need to wrap `Use checkboxes to:` text with `span` tag
This way all out mixin styles will be applied both to the header title and to the list items without using `!important`

2023-10-08 10:43 UTC, SergeyRoyt commented on src/components/Checkbox/__stories__/checkbox.stories.scss
> +    font-family :var(--font-family) !important;
Then this won't be needed too

2023-10-08 10:45 UTC, SergeyRoyt requested changes
Hey, @SoumyadiptoPal!
Thanks for the efforts! Left a few notes needed to finish the job! 💪

2023-10-08 10:48 UTC, SergeyRoyt commented
Btw, it's always better to name the branches with some semantic names, e.g. in this case it could have been smth like
`docs/checkbox-usage-guidelines-font`
Doesn't really matter in this case though, no worries, just a tip for the future :)

2023-10-08 16:41 UTC, SoumyadiptoPal commented
> Btw, it's always better to name the branches with some semantic names, e.g. in this case it could have been smth like `docs/checkbox-usage-guidelines-font` Doesn't really matter in this case though, no worries, just a tip for the future :)

Thank out for your advice. Will try to follow this from next time.👍👍

2023-10-08 16:42 UTC, SoumyadiptoPal commented
@SergeyRoyt I have updated the code.

2023-10-09 07:26 UTC, SergeyRoyt approved these changes
Looks great, thanks!!
Please, also write a comment under the issue itself, so I can assign it to you and you'll get your Hactoberfest reward :)

2023-10-09 07:26 UTC, merged