Replace tip alpha warning deprecated warning with vibe storybook components
mondaycom/monday-ui-react-core pull request #1628
Opened 2023-10-09 15:43 UTC by talkor

https://monday.monday.com/boards/3532714909/pulses/5296950950

2023-10-09 15:49 UTC, talkor commented on webpack/published-storybook-components.js
> -  "storybook/Tip": "storybook/components/tip/tip.jsx"
Apparently these are the only two components that were exported as `storybookComponents`, the rest is commented-out and I guess they will be moved to `vibe-storybook-components` as well which makes the build scripts redundant. I'm not sure who's consuming them, I looked up in GH search and couldn't find but I'm not 100% sure

2023-10-10 12:14 UTC, SergeyRoyt commented on package.json
> -    "./storybookComponents": "./dist/storybook/index.js",
We probably shouldn't remove this endpoint - it's a breaking change
I think we should consider doing it in the next major version

2023-10-10 12:15 UTC, SergeyRoyt commented on scripts/build-utils.js
> -  const imports = ["import 'vibe-storybook-components/index.css';"];
This line should remain I guess

2023-10-10 12:16 UTC, SergeyRoyt commented on scripts/build-utils.js
> -  exports.push("export * from 'vibe-storybook-components'");
As well as this reexport from vibe-storybook-components

2023-10-10 12:20 UTC, SergeyRoyt requested changes
Let's not do the breaking change for now and leave reexport of `vibe-storybook-components` on `/storybookComponents` endpoint. The rest can be removed, but, please, make sure that /storybookComponents is still building and working correctly

2023-10-10 14:51 UTC, talkor commented
> Let's not do the breaking change for now and leave reexport of `vibe-storybook-components` on `/storybookComponents` endpoint. The rest can be removed, but, please, make sure that /storybookComponents is still building and working correctly

@SergeyRoyt 
Correct me if I'm mistaken but looks like those all scripts are for publishing just the Tip and AlphaWarning components. Including the export and import statements in the script. If we do not want to deploy breaking changes it means that those existing components should remain as they are, not sure it's being used though

2023-10-11 08:29 UTC, SergeyRoyt commented
> > Let's not do the breaking change for now and leave reexport of `vibe-storybook-components` on `/storybookComponents` endpoint. The rest can be removed, but, please, make sure that /storybookComponents is still building and working correctly
> 
> @SergeyRoyt Correct me if I'm mistaken but looks like those all scripts are for publishing just the Tip and AlphaWarning components. Including the export and import statements in the script. If we do not want to deploy breaking changes it means that those existing components should remain as they are, not sure it's being used though

One of the scripts is also adding reexport of vibe-storybook-components - this should be remain as it is, everything else can be removed
And regarding Tip and AlphaWarning and its not breaking cause they will be replaced with reexport from vibe-storybook-components

2023-10-12 10:55 UTC, SergeyRoyt approved these changes
Looks great now!

2023-10-15 07:48 UTC, merged