fix: colorpicker indicator is dissapearing when color is selected
mondaycom/monday-ui-react-core pull request #1657
Opened 2023-10-12 14:02 UTC by sayyedarib

Fixes #1655 

**before**
![Screenshot from 2023-10-12 19-26-12](https://github.com/mondaycom/monday-ui-react-core/assets/90370535/ec473fd7-9d88-43af-88fd-696f1f05591c)
![Screenshot from 2023-10-12 19-26-00](https://github.com/mondaycom/monday-ui-react-core/assets/90370535/a30a7175-0912-40c0-932e-eaae84f1e105)

**now**
![1](https://github.com/mondaycom/monday-ui-react-core/assets/90370535/e3828cb1-f73b-47d3-ae85-2344a3a9588c)

![2](https://github.com/mondaycom/monday-ui-react-core/assets/90370535/a05ea717-8037-4d8b-ba77-cad0e4e966c9)

#### Basic

- [x] Used plop (`npm run plop`) to create a new component.
- [x] PR has description.
- [x] New component is functional and uses Hooks.
- [x] Component is written in TypeScript.

#### Style

- [x] Styles are added to `NewComponent.modules.scss` file inside the `NewComponent` folder.
- [x] Component uses CSS Modules.
- [x] Design is compatible with [Monday Design System](https://design.monday.com/).
- [x] Styles are defined using [monday-ui-style](https://github.com/mondaycom/monday-ui-style) tokens
- [x] Displays correctly in all the themes

#### Storybook

- [x] Stories were added to `/src/components/NewComponent/__stories__/NewComponent.stories.mdx` file.
- [x] Stories include all flows of using the component.
- [x] Stories implemented using [vibe-storybook-components](https://github.com/mondaycom/vibe-storybook-components) components and tokens.

#### Tests

- [x] Tests are compliant with [TESTING_README.md](TESTING_README.md) instructions.

#### Accessibility

- [x] Component is accessible.
- [x] Component is compatible with [Vibe Accessibility Guidelines](https://style.monday.com/?path=/docs/foundations-accessibility--page)

2023-10-12 14:54 UTC, SergeyRoyt commented on src/components/ColorPicker/components/ColorPickerItemComponent/ColorPickerItemComponent.tsx
> -      SelectedIndicatorIcon,
I think it just should have a default value of `ColorIndicatorIcon`

2023-10-12 14:56 UTC, SergeyRoyt requested changes
What you are proposing is a removing this feature completely - we can't do it, it's a breaking change
I believe that instead this `SelectedIndicatorIcon` if undefined should be equal to `SelectedIndicatorIcon`

2023-10-14 10:03 UTC, sayyedarib commented
@SergeyRoyt let me know if the changes are ok ?

2023-10-15 14:08 UTC, SergeyRoyt requested changes
Hey @sayyedarib!
The logic here is correct, but I believe it would work the same if you revert this line and just in props deconstruction give it default value and in terms of code cleanliness it'd look better
![image](https://github.com/mondaycom/monday-ui-react-core/assets/104433616/206f9047-e90e-4340-8bf4-e09b4e3d8a2d)

2023-10-15 18:42 UTC, SergeyRoyt approved these changes
Great job!  💪
Congrats with the first contribution to Vibe! 🥳🥳

2023-10-15 18:46 UTC, merged