Add support in tipseen component for: submitButtonText & submitButtonOnClick & dismissButtonText & dismissButtonOnClick & hideWhenReferenceHidden
mondaycom/monday-ui-react-core pull request #323
Opened 2021-11-04 14:30 UTC by hadasfa

## Go over this checklist before submitting your Pull Request

Description: Add support in tipseen component for: submitButtonText & submitButtonOnClick & dismissButtonText & dismissButtonOnClick & hideWhenReferenceHidden.
The change in the button props is moshe tzemach idea after reviewing the tipseen in monolith changes.
The hideWhenReferenceHidden support is for fixing the monolith bug.

### Updating existing component
#### Basic
- [v] PR has description
- [ ] Changes to the component are backward compatible (including selectors structure). If not - add to the title of the PR "BREAKABLE_CHANGE""
- [v] All changes to the component are reflected in the ReadMe
- [ ] If component is old and was not compliant with the latest guidelines - it was fixed (optional) 
#### Style
- [ ] CSS selectors are named using [BEM convention](http://getbem.com/naming/) 
- [ ] Design is compatible with [Monday Design System](https://design.monday.com/)
#### Storybook
- [v] All the changes to the component should be reflected in the Storybook.
- [v] Component passed Accessibility Plugin checks
#### Tests
- [v] All current tests are passing
- [v] New functionality is covered with tests
- [v] Tests are compliant with TESTING_README.md instructions

2021-11-04 15:01 UTC, hadasfa commented on src/components/Tipseen/__stories__/tipseen.stories.js
> +          submitButtonText={text("Submit button text", "Submit button text")}
In evginy design the button called "submit" but in the monolith it's standard name is got it.
so, here the api remain the same but in the monolith I am using tipseen content wrapper which expect the receive "gotItButtonText" and "gotItCallback" (which there I also close the tipseen with the redux monolith mechanism).
I think that "gotItButtonText" and "gotItCallback" will be little bit weird inside an open source library api. what do you think?

2021-11-04 15:24 UTC, orrgottlieb requested changes

2021-11-04 15:24 UTC, orrgottlieb commented on src/components/Tipseen/TipseenContent.jsx
> +  debugger;
remove debugger;

2021-11-07 07:40 UTC, orrgottlieb approved these changes

2021-11-07 07:40 UTC, orrgottlieb commented on src/helpers/backwardCompatibilityForProperties.js
> +export function backwardCompatibilityForProperties(valuesArrayByMostUpdateNaming, defaultValue) {
1. please add defaults to the arguments `EMPTY_ARRAY`
2. Please consider adding useMemo on the spread of the array which is being passed.

2021-11-07 07:40 UTC, orrgottlieb commented on src/components/Tipseen/TipseenContent.jsx
> +  } = submitButtonProps || {};
EMOTY_OBJECT

2021-11-07 07:40 UTC, orrgottlieb commented on src/components/Tipseen/TipseenContent.jsx
> +  } = dismissButtonProps || {};
EMOTY_OBJECT

2021-11-07 09:18 UTC, merged