Feature/dorsh/dropdown
mondaycom/monday-ui-react-core pull request #37
Opened 2020-12-06 11:55 UTC by DorShakedMonday

Description: **New component - Dropdown**

- Added Dropdown component based on react-select, react-virtualized and react-select-virtualized.
- Fixed Icon props naming
- Fixed FieldLabel usage of Icon component

### Adding new component
#### Basic
- [ ] Used plop (npm run plop) to create a new component. This command will create a folder for your component and will update index.js file
- [ ] PR has description
- [ ] New component is functional and using React Hooks. 
- [ ] Component defines PropTypes
#### Style
- [ ] Styles are added to NewComponent.scss file inside of the NewComponent folder
- [ ] CSS selectors are named using [BEM convention](http://getbem.com/naming/) 
- [ ] Design is compatible with [Monday Design System](https://design.monday.com/)
#### Storybook
- [ ] Stories were added to /src/NewComponent/__stories__/NewComponent.stories.js file
- [ ] Stories include sandbox story with knobs for each property
- [ ] Stories include all flows of using the component
- [ ] Component passed Accessibility Plugin checks
#### Tests
- [ ] Tests are compliant with TESTING_README.md instructions

2020-12-06 13:00 UTC, orrgottlieb requested changes
Awesome awesome awesome PR.
I have some requests but overall amazing PR
Thank you

2020-12-07 17:42 UTC, DorShakedMonday commented on src/components/Dropdown/Dropdown.jsx
> +  const DropdownIndicator = useCallback(
Done

2020-12-07 17:42 UTC, DorShakedMonday commented on src/components/Dropdown/Dropdown.jsx
> +  if (isVirtualized) {
We discussed this and decided to leave it this way and maybe separate later.

2020-12-07 17:43 UTC, DorShakedMonday commented on src/components/Dropdown/Dropdown.jsx
> +Dropdown.propTypes = {
XD

2020-12-07 17:43 UTC, DorShakedMonday commented on src/components/Dropdown/Dropdown.styles.js
> +  switch (size) {
Mistake, the code was different at the start hhh

2020-12-07 18:35 UTC, DorShakedMonday commented on src/components/Dropdown/Dropdown.scss
> +    max-height: 300px;
Done

2020-12-07 18:39 UTC, DorShakedMonday commented on src/components/Dropdown/Dropdown.styles.js
> +  switch (size) {
Done

2020-12-08 12:54 UTC, orrgottlieb commented on src/components/FieldLabel/FieldLabel.jsx
> +          icon
should have the icon passed to the icon component

2020-12-08 12:54 UTC, orrgottlieb commented on src/components/Icon/Icon.jsx
> +          tabIndex={externalTabIndex || tabindex}
this could be an issue if the external is 0 and the tabIndex might be for example -1 ?

2020-12-08 13:12 UTC, orrgottlieb approved these changes

2020-12-08 13:12 UTC, merged