added indexes for other idGetter usages
mondaycom/monday-ui-react-core pull request #376
Opened 2021-12-05 16:23 UTC by etaylib

2021-12-05 17:00 UTC, MosheZemah approved these changes

2021-12-06 08:47 UTC, hadasfa requested changes

2021-12-06 08:47 UTC, hadasfa commented on src/components/VirtualizedList/virtualized-list-service.js
> +  const lastExistingItemId = idGetter(lastExistingItem, i);
Please fix eslint and tests errors :)

2021-12-06 08:58 UTC, MosheZemah requested changes

2021-12-06 08:58 UTC, MosheZemah commented on src/components/VirtualizedList/virtualized-list-service.js
> +  const lastExistingItemId = idGetter(lastExistingItem, i);
```suggestion
  const lastExistingItemId = idGetter(lastExistingItem, items.length - 1);
```

2021-12-06 08:58 UTC, MosheZemah approved these changes

2021-12-06 13:01 UTC, merged