amitha/feature/expand-collapse-component
mondaycom/monday-ui-react-core pull request #63
Opened 2021-02-10 15:57 UTC by amit-hanoch

Description: New Component Added - ExpandCollapse

### Adding new component
#### Basic
- [V] Used plop (npm run plop) to create a new component. This command will create a folder for your component and will update index.js file
- [V] PR has description
- [V] New component is functional and using React Hooks. 
- [V] Component defines PropTypes
- [ ] There is Readme for the component, which explains the main aspects of how to use it
#### Style
- [V] Styles are added to NewComponent.scss file inside of the NewComponent folder
- [V] CSS selectors are named using [BEM convention](http://getbem.com/naming/) 
- [V] Design is compatible with [Monday Design System](https://design.monday.com/)
#### Storybook
- [V] Stories were added to /src/NewComponent/__stories__/NewComponent.stories.js file
- [ ] Stories include sandbox story with knobs for each property
- [V] Stories include all flows of using the component
- [ ] Component passed Accessibility Plugin checks
#### Tests
- [ ] Tests are compliant with TESTING_README.md instructions

2021-02-15 08:37 UTC, orrgottlieb requested changes

2021-02-15 11:12 UTC, amit-hanoch commented on src/components/ExpandCollapse/ExpandCollapse.jsx
> +            icon={DropdownChevronDown}
After a talk with the design team, we will add animation to flip the arrow so we won't change the icon for now

2021-02-15 16:12 UTC, tomer-monday approved these changes

2021-02-16 10:33 UTC, orrgottlieb commented on src/components/ExpandCollapse/ExpandCollapse.jsx
> +            {headerComponentRenderer && headerComponentRenderer()}
this should be onClickCapture - as the inner component might catch the event before it bubbels

2021-02-16 10:33 UTC, orrgottlieb commented on src/components/ExpandCollapse/ExpandCollapse.jsx
> +              icon={DropdownChevronDown}
pass icon in the props?

2021-02-16 13:08 UTC, orrgottlieb approved these changes

2021-02-16 13:08 UTC, merged