scroll combobox fix
mondaycom/monday-ui-react-core pull request #736
Opened 2022-07-04 13:45 UTC by mentaman

#### Basic
- [ ] Used plop (`npm run plop`) to create a new component.
- [ ] PR has description.
- [ ] New component is functional and uses Hooks. 
- [ ] Component defines [`PropTypes`](https://reactjs.org/docs/typechecking-with-proptypes.html).
#### Style
- [ ] Styles are added to `NewComponent.modules.scss` file inside of the `NewComponent` folder.
- [ ] Component uses CSS Modules.
- [ ] Design is compatible with [Monday Design System](https://design.monday.com/).
#### Storybook
- [ ] Stories were added to `/src/NewComponent/__stories__/NewComponent.stories.js` file.
- [ ] Stories include all flows of using the component.
#### Tests
- [ ] Tests are compliant with [TESTING_README.md](TESTING_README.md) instructions.

2022-07-05 08:49 UTC, RonNachmany requested changes

2022-07-05 08:49 UTC, RonNachmany commented on src/components/Combobox/Combobox.jsx
> +            scrollInCombobox={scrollInCombobox}
why prop??

2022-07-05 11:27 UTC, mentaman commented on src/components/Combobox/Combobox.jsx
> +            scrollInCombobox={scrollInCombobox}
gradual release :o

2022-07-05 17:54 UTC, mentaman commented on src/components/Combobox/components/ComboboxItems/ComboboxItems.jsx
> +            scrollRef: renderOnlyVisibleOptions ? null : ref,
The ref is not correct with virtualize, so didnt support for now

2022-07-06 06:55 UTC, RonNachmany approved these changes

2022-07-27 06:50 UTC, hadasfa approved these changes

2022-07-27 06:50 UTC, merged