refactor: migrate Divider in typescript
mondaycom/monday-ui-react-core pull request #916
Opened 2022-10-04 09:50 UTC by aayushbisen

Convert `Divider` in TypeScript.

Closes #896

#### Basic
- [ ] Used plop (`npm run plop`) to create a new component.
- [x] PR has description.
- [ ] New component is functional and uses Hooks. 
- [ ] Component defines [`PropTypes`](https://reactjs.org/docs/typechecking-with-proptypes.html).
#### Style
- [ ] Styles are added to `NewComponent.modules.scss` file inside of the `NewComponent` folder.
- [ ] Component uses CSS Modules.
- [x] Design is compatible with [Monday Design System](https://design.monday.com/).
#### Storybook
- [ ] Stories were added to `/src/NewComponent/__stories__/NewComponent.stories.js` file.
- [x] Stories include all flows of using the component.
#### Tests
- [x] Tests are compliant with [TESTING_README.md](TESTING_README.md) instructions.

2022-10-04 10:03 UTC, orrgottlieb requested changes
Thank you so much. Awesome work! i have a few comments 🙏

2022-10-04 10:03 UTC, orrgottlieb commented on src/components/Divider/__stories__/Divider.stories.mdx
> +  enumPropNamesArray: ["directions"]
why did you change this ?

2022-10-04 10:03 UTC, orrgottlieb commented on src/components/Divider/Divider.tsx
> +  className = undefined,
please leave the `propTypes` for now 🙏

2022-10-04 10:03 UTC, orrgottlieb commented on src/components/Divider/__tests__/divider.jest.tsx
> +  const tree = renderer.create(<Divider/>).toJSON();
prettier fix?

2022-10-04 10:17 UTC, aayushbisen commented on src/components/Divider/__tests__/divider.jest.tsx
> +  const tree = renderer.create(<Divider/>).toJSON();
Yes.

2022-10-04 10:18 UTC, aayushbisen commented on src/components/Divider/Divider.tsx
> +  className = undefined,
Sure.

2022-10-04 10:43 UTC, aayushbisen commented
@orrgottlieb Done the changes for comments.

I noticed that VibeComponentProps has relative path in import in other PR should I do the same?

2022-10-04 10:45 UTC, orrgottlieb commented on src/components/Divider/__stories__/Divider.stories.mdx
> +  enumPropNamesArray: ["directions"]
thanks 🙏

2022-10-04 10:45 UTC, orrgottlieb commented on src/components/Divider/Divider.tsx
> +  className = undefined,
thank you

2022-10-04 10:46 UTC, orrgottlieb commented
@aayushbisen regarding the relative imports - please use relative improts, we need this due to internal usage

2022-10-07 08:14 UTC, orrgottlieb approved these changes
@aayushbisen thank you so much!
Approved, Merged and i will add the correct label to the issue

2022-10-07 08:15 UTC, merged