Migrated Radio Button to typescript
mondaycom/monday-ui-react-core pull request #918
Opened 2022-10-04 14:56 UTC by Suman94310

#### Basic
- [ ] Used plop (`npm run plop`) to create a new component.
- [X] PR has description.
- [X] New component is functional and uses Hooks. 
- [X] Component defines [`PropTypes`](https://reactjs.org/docs/typechecking-with-proptypes.html).
#### Style
- [ ] Styles are added to `NewComponent.modules.scss` file inside of the `NewComponent` folder.
- [ ] Component uses CSS Modules.
- [ ] Design is compatible with [Monday Design System](https://design.monday.com/).
#### Storybook
- [ ] Stories were added to `/src/NewComponent/__stories__/NewComponent.stories.js` file.
- [X] Stories include all flows of using the component.
#### Tests
- [X] Tests are compliant with [TESTING_README.md](TESTING_README.md) instructions.

## Description
This P.R. migrates "RadioButton" and it's children component( "Clickable" ) to typescript.
this resolves #904

2022-10-06 06:31 UTC, orrgottlieb requested changes
Hi @Suman94310 
thank you so much, i have some small comments 🙏 
great PR!!

2022-10-06 06:31 UTC, orrgottlieb commented on src/components/Clickable/Clickable.tsx
> +  role?: string;
Please change this to `AriaRole` 🙏

2022-10-06 06:31 UTC, orrgottlieb commented on src/components/Clickable/Clickable.tsx
> +  onClick?: (event: KeyboardEvent) => void;
This could also be a `MouseEvent`

2022-10-06 06:31 UTC, orrgottlieb commented on src/components/Clickable/Clickable.tsx
> +  style?: object;
we have CSSProperites type

2022-10-06 18:50 UTC, Suman94310 commented
Thanks for reviewing my PR @orrgottlieb, I have updated the PR .

2022-10-07 08:09 UTC, orrgottlieb approved these changes
Thank you @Suman94310 for this awesome PR!
Approved, Will merged and will add the appropriate tag for the issue

2022-10-07 08:09 UTC, orrgottlieb commented on src/components/Clickable/Clickable.tsx
> +  elementType?: keyof JSX.IntrinsicElements | string;
nice!

2022-10-07 08:10 UTC, merged