Migrate Flex to typescript
mondaycom/monday-ui-react-core pull request #920
Opened 2022-10-05 19:25 UTC by piotrski

This PR migrates `Flex` component to typescript.
Resolves #909 

#### Basic
- [ ] Used plop (`npm run plop`) to create a new component.
- [ ] PR has description.
- [ ] New component is functional and uses Hooks. 
- [ ] Component defines [`PropTypes`](https://reactjs.org/docs/typechecking-with-proptypes.html).
#### Style
- [ ] Styles are added to `NewComponent.modules.scss` file inside of the `NewComponent` folder.
- [ ] Component uses CSS Modules.
- [x] Design is compatible with [Monday Design System](https://design.monday.com/).
#### Storybook
- [x] Stories were added to `/src/NewComponent/__stories__/NewComponent.stories.js` file.
- [x] Stories include all flows of using the component.
#### Tests
- [x] Tests are compliant with [TESTING_README.md](TESTING_README.md) instructions.

2022-10-06 06:12 UTC, orrgottlieb requested changes
This is an awesome job!
i have some small comments 🙏 
thank you so much

2022-10-06 06:12 UTC, orrgottlieb commented on src/components/Flex/Flex.tsx
> +  onClick?: React.MouseEventHandler;
Hi @piotrski
the onClick could also be from a keyboard event, please add it as well

2022-10-06 06:12 UTC, orrgottlieb commented on src/components/Flex/Flex.tsx
> +export default {
for consistency in the code base, 
please export default the Component and assign `justify`, `align`, `gaps` and `directions` as properties to the component 🙏

2022-10-06 06:12 UTC, orrgottlieb commented on src/components/Flex/__stories__/Flex.stories.mdx
> +export const metaSettings = createStoryMetaSettings({
this is awesome, thank you 🙏

2022-10-06 06:12 UTC, orrgottlieb commented on src/components/Flex/Flex.tsx
> +const Flex: VibeComponent<FlexProps, HTMLElement> = forwardRef(
please keep the `propTypes` on the Component itself 🙏

2022-11-24 16:25 UTC, SergeyRoyt commented
Closed in favor of https://github.com/mondaycom/monday-ui-react-core/pull/1006

2022-11-24 16:25 UTC, closed without merging